### ISSUE TITLE
htmlspecialchars() error introduced in 2fa-login.blade

### ISSUE THREAD

**Issue by MatticusPrime29** [vormkracht10/filament-2fa#69] opened 2024-12-17 16:06 UTC
> This introduces a bug:
> 
> 
> 
> htmlspecialchars(): Argument #1 ($string) must be of type string, array given
> 
> 
> 
> 
> 
> in this method from vendor/laravel/framework/src/Illuminate/Support/helpers.php :
> 
> 
> 
> ```
> 
> function e($value, $doubleEncode = true)
> 
>     {
> 
>         if ($value instanceof DeferringDisplayableValue) {
> 
>             $value = $value->resolveDisplayableValue();
> 
>         }
> 
> 
> 
>         if ($value instanceof Htmlable) {
> 
>             return $value->toHtml();
> 
>         }
> 
> 
> 
>         if ($value instanceof BackedEnum) {
> 
>             $value = $value->value;
> 
>         }
> 
> 
> 
>         return htmlspecialchars($value ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8', $doubleEncode);
> 
>     }
> 
> ```
> 
> 
> 
> Called from this blade component:
> 
> 
> 
> ```
> 
> <?php $component->withAttributes(['type' => 'submit','class' => 'w-full','style' => 'background-color: '.e(filament()->getCurrentPanel()->getColors()['primary']).';']); ?>
> 
> 
> 
> ```
> 
> 
> 
> The value passed into e() is expected to be a string. But filement()->getCurrentPanel()->getColors()['primary'] is an array 

 _Originally posted by @MatticusPrime29 in [8b12742](https://github.com/vormkracht10/filament-2fa/commit/8b12742c940be06f3daa6783f6c86f4acc409a5e#commitcomment-150456182)_

**Comment by Baspa** [comment] 2024-12-18 10:26
Can you provide me reproduction repository or an example on how to reproduce this? I am not able to reproduce it. @MatticusPrime29

**Comment by Baspa** [comment] 2024-12-19 12:34
Will be fixed in #70

**Closed by Baspa** 2024-12-19 12:34 UTC
Labels: needs reproduction repo
